### ISSUE TITLE
🐛 Fix: Closing order does not work with an order object

### ISSUE THREAD

**Issue by atrefonas** [algodex/algodex-sdk#213]
# ℹ Overview
```

await api.closeOrder({
      'asset': order.asset,
      'address': order.address,
      'price': order.price,
      'amount': order.amount,
      'execution': 'close',
      'type': order.type,
    }); 
```

Uncaught TypeError TypeError: Must have valid algod client!!!
    at structure (/Users/a3voices/algodex-sdk/lib/order/structure/structure.js:49:58)
    at <anonymous> (/Users/a3voices/algodex-sdk/lib/AlgodexApi.js:506:16)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

### 💻 System Configuration

- Operating System:
    - Edition: 
    - Version: 
    - Build: 
- Browser:
    - Type: 
    - Version:

**Comment by atrefonas** [comment]
I see it's being used in the PR-400 in algodex-react, however I don't see this documented anywhere:

        const cancelOrderPromise = closeOrder({
          address: ownerAddress,
          version,
          price: Number(formattedPrice),
          amount: Number(formattedASAAmount),
          total: Number(formattedPrice) * Number(formattedASAAmount),
          asset: { id: assetId, decimals },
          assetId,
          type: cellData.type.toLowerCase(),
          appId,
          contract: {
            creator: ownerAddress
          },
          wallet
        })

**Comment by atrefonas** [comment]
Finally got it to work after adding all of this:

   ```
 const cancelOrderObj = {
      address: dbOrder.address,
      version: dbOrder.version,
      price: dbOrder.price,
      amount: dbOrder.amount,
      total: dbOrder.price * dbOrder.amount,
      asset: {id: assetId, decimals: 6},
      assetId: dbOrder.assetId,
      type: dbOrder.type,
      appId: appId,
      contract: {
        creator: dbOrder.contract.creator,
        lsig: new LogicSigAccount(dbOrder.contract.lsig.lsig.logic.data),
      },
      wallet: api.wallet,
      client: api.algod,
    };
```

**Comment by atrefonas** [comment]
This is how difficult it currently is to close orders using the Algodex orderbook alone: 

https://github.com/algodex/algodex-sdk-examples/blob/main/cancel-all-orders/cancel-all-orders.js

Should get massively simplified.
